### ISSUE TITLE
Tutorials for Linux101 and commonly used Linux commands

### ISSUE THREAD

**Issue by seisman** [seismo-learn/seismology101#67]
**Key Points:** Learn by practicing.

## Linux 101

**CLI**
- [x] What's CLI? Why CLI?
- [x] How to open a terminal

**File System**
- [x]  Familiar with the file system, and especially the **HOME** directory
- [x] Operating directories and files:  `pwd`, `ls`, `cd`, `mkdir`, `rmdir`, `cp`, `mv`, `rm`, `touch`, `ln`
- [x] relative path and absolute path
- [x] file permission: `rwx`,`chmod`, `sudo`

**Shell**
- [x] Use wildcards `?`, `*`, `[]` to match mutiple files or directories
- [x] redirection `>`, `>>`, `<` and `<< EOF`
- [x] Pipe
~~- [ ] regular expression：https://regex101.com/~~

**Environmental Path**
- [x] **PATH**：`echo $PATH`
- [x] `~/.bashrc` and `~/.zshrc`
- [x] find command path: `which`, `whereis`

**Editor**
- [x] Recommend vs code
- [x] Learn the vim editor

## Commonly used commands

- [x] **Read file**

  - `cat`
  - `head`
  - `tail`
  - `less`

- [x] **Process file**

  - `diff`
  - `gawk`
  - `grep`
  - `sed`
  - `sort`
  - `uniq`
  - `wc`

- [x] **Search file**

  - `locate`
  - `find`

- [x] **Transfer file**

  - `rsync`
  - `scp`

-  [x] **Download file**

    - `wget` | `curl`

- [x] **Compress file**

  - `tar`

- [x] **System manage**

  - `df`
  - `du`
  - `top`

- [x] **Remote login**

  - `ssh`

## References

Resources for Linux (Chinese)
- 阮一峰 Bash 脚本教程: https://wangdoc.com/ | https://www.bookstack.cn/books/bash-tutorial
- [Linux 101](https://101.lug.ustc.edu.cn/) (by USTC LUG)

Resources for commands:

- Linux 命令大全: http://man.linuxde.net

Resources that we do **NOT** recommend:

- 鸟哥的 Linux 私房菜 (CentOS): [基础学习篇第三版](http://cn.linux.vbird.org) \| [基础学习篇第四版](https://wizardforcel.gitbooks.io/vbird-linux-basic-4e/content/index.html): Too long; Too old; Use root in examples.
- https://blog.seisman.info/simple-guide-to-seismology/: Something are old and the other included above.
- [Basics of Linux and the vim editor](https://msu.edu/~allenmc/GLG873/2017-Linux_and_VI_basics.pdf): by Dr. Allen McNamara (a geophysics professor at MSU EES): Dead link
- https://migg-ntu.github.io/SeisTomo_Tutorials/computer/LinuxmacOS-basis.html: Already included above
- https://migg-ntu.github.io/SeisTomo_Tutorials/computer/command-lines.html: Already included above
- tldr: https://101.lug.ustc.edu.cn/Ch03/#tldr: Done in #110 
- CLI and Filesystem: http://www.1zlab.com/wiki/Hello-Ubuntu/why-command/: Already included in #169 and #184.
- [Commonly-used Unix commands](https://igpppublic.ucsd.edu/~shearer/COMP233/Agnew_UNIX_onepage.pdf): One page, English, so useless.
- [The Missing Semester of Your CS Education](https://missing.csail.mit.edu/) | [中文版](https://missing-semester-cn.github.io/)： the pages are not good for readers.
- [Introduction to Unix](http://geophysics.eas.gatech.edu/classes/Intro_Unix/): by Andrew Newman (a geophysics professor at Georgia Tech): A little old
- [Introduction to Computing](https://igpppublic.ucsd.edu/~shearer/COMP233/): by Peter Shearer (a geophysics professor at USCD) a little old and some are not about Linux
- [The Linux Command Line](http://linuxcommand.org/tlcl.php) | [中文版](http://billie66.github.io/TLCL/index.html) (Github翻译项目) | [中文版](https://www.kancloud.cn/thinkphp/linux-command-line) (看云)
- [Linux学习笔记](https://pan.baidu.com/s/1Eo7xFt8UUbXL21OREXUPGA) (by 华为工程师; 提取码 `7v19`)
- [UNIX Tutorial for Beginners](http://www.ee.surrey.ac.uk/Teaching/Unix/): One of the most popular online tutorials by electronic engineers
- Linux 命令手册: http://linux.51yip.com: not good
- Linux 命令大全: https://www.runoob.com/linux/linux-command-manual.html: not good
- Linux 命令大全: https://hezhiqiang.gitbook.io/linux/: not good

**Comment by core-man** [comment]
Also refer to:
- https://migg-ntu.github.io/SeisTomo_Tutorials/computer/LinuxmacOS-basis.html
- https://migg-ntu.github.io/SeisTomo_Tutorials/computer/command-lines.html

**Comment by core-man** [comment]
I'd like to suggest we could first think about commonly used commands and try to finish it before we start Linux101.

**Comment by seisman** [comment]
> I'd like to suggest we could first think about commonly used commands and try to finish it before we start Linux101.

What's your reason?

**Comment by core-man** [comment]
> > I'd like to suggest we could first think about commonly used commands and try to finish it before we start Linux101.
> 
> What's your reason?

It's easier and Linux101 needs them also.

**Comment by seisman** [comment]
Are you going to talk about `mkdir` in both linux101 and commands?

**Comment by core-man** [comment]
> Are you going to talk about `mkdir` in both linux101 and commands?

No... We better only have one.

**Comment by seisman** [comment]
We can draft a TOC first and then fill in the content.

**Comment by core-man** [comment]
> We can draft a TOC first and then fill in the content.

That's a good idea.

**Comment by core-man** [comment]
We may finally come to Linux101 soon. I am thinking about how to organize this chapter.

See a quick TOC:

**CLI**
- What's CLI? Why CLI?
- How to open a terminal

**File system**
- Familiar with the file system, and especially the **HOME** directory
- Operating directories and files:  `pwd`, `ls`, `cd`, `mkdir`, `rmdir`, `cp`, `mv`, `rm`, `touch`, `ln`
- file permission `rwx` and `chmod`
- `sudo`
- relative path and absolute path

**Environment**
- **PATH**：echo
-  `~/.bashrc` and `~/.zshrc`
- command path: `which`, `whereis`

**TODO**
- redirection `>`, `>>`, `<<` and `EOF`
- Pipe
- Use wildcards `?`, `*`, `[]` to match mutiple files or directories
- regular expression
- `/etc/hosts`

**Vim**
- Learn the vim editor, which is the only text editor available on Linux servers.

**Shell**
- What is a Shell (bash/csh) script? https://www.tutorialspoint.com/unix/unix-what-is-shell.htm

**Comment by core-man** [comment]
I will work on CLI today.

**Comment by core-man** [comment]
**Editor**

- vim
  - https://www.runoob.com/linux/linux-vim.html
  - https://missing-semester-cn.github.io/2020/editors/
  - https://github.com/vim/vim
  - http://billie66.github.io/TLCL/book/chap13.html
- vs code

**Comment by core-man** [comment]
**Shell**
- Intro
  - https://101.lug.ustc.edu.cn/Appendix/glossary/#shell
  - https://101.lug.ustc.edu.cn/Ch02/#what-shell
  - https://101.lug.ustc.edu.cn/Ch06/#shell-scripts
  - https://missing-semester-cn.github.io/2020/shell-tools/
  - http://billie66.github.io/TLCL/book/chap02.html
- I/O, pipe
  - https://101.lug.ustc.edu.cn/Ch09/#redirect-and-pipe
  - http://billie66.github.io/TLCL/book/chap07.html
  - https://docs.gmt-china.org/latest/tutorial/scripting/#bash
- wildcards
  - https://101.lug.ustc.edu.cn/Ch09/#special-char
  - http://billie66.github.io/TLCL/book/chap05.html
- regular expression
  - https://101.lug.ustc.edu.cn/Ch09/#regular-expression
  - https://missing-semester-cn.github.io/2020/data-wrangling/
  - https://missing-semester-cn.github.io/2020/command-line/

**Comment by core-man** [comment]
**Environment**

- https://101.lug.ustc.edu.cn/Ch06/#_3
- http://billie66.github.io/TLCL/book/chap12.html

**Comment by core-man** [comment]
I feel we may split those sections into different `.rst` files similar to languages. It is a little long for new babies to read one-page Linux101.

**Comment by seisman** [comment]
I agree.

**Comment by core-man** [comment]
@seisman We may still have to put some recommending resources on the Linux101 page https://seismo-learn.org/seismology101/computer/linux101/ before we make a final review and check for the whole computer part.

**Comment by core-man** [comment]
We finally finish all the planned sections for Linux101. Let's make a final review of the computer part @seismo-learn/contributors

**Comment by wangliang1989** [comment]
1. 我记忆里Mac如果系统有重大更新，xcode-select --install有时需要重新执行一次，然后一些软件需要重新编译。
2. 新版的hb现在已经不把软件安装在/usr/local/bin/下面了，之前好像说过的。我在这里看到没有改动：https://seismo-learn.org/seismology101/computer/macos-setup/。
3. 从Catalina开始，Mac的默认shell是zsh，intel的警告那里写的还是bashrc

> We finally finish all the planned sections for Linux101. Let's make a final review of the computer part @seismo-learn/contributors

**Comment by core-man** [comment]
> 1. 我记忆里Mac如果系统有重大更新，xcode-select --install有时需要重新执行一次，然后一些软件需要重新编译。

可以加一个 note。

> 2. 新版的hb现在已经不把软件安装在/usr/local/bin/下面了，之前好像说过的。我在这里看到没有改动：[https://seismo-learn.org/seismology101/computer/macos-setup/。](https://seismo-learn.org/seismology101/computer/macos-setup/%E3%80%82)

[安装](https://seismo-learn.org/seismology101/computer/macos-setup/#id3)的最后一个note里说明了。

> 3. 从Catalina开始，Mac的默认shell是zsh，intel的警告那里写的还是bashrc

警告信息是和 Linux 装机指南通用的。

**Comment by core-man** [comment]
> 1. 我记忆里Mac如果系统有重大更新，xcode-select --install有时需要重新执行一次，然后一些软件需要重新编译。

done in #266.
